[GLOBAL]
pants_version = "2.14.0"
backend_packages = [
  "pants.backend.experimental.python",
  "pants.backend.experimental.python.lint.autoflake",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

[anonymous-telemetry]
enabled = true
repo_id = "336EC375-B2BA-48AA-B3FC-028F63AFDF2A"


[mypy]
args = "--namespace-packages --explicit-package-bases"


[python]
interpreter_constraints = [">=3.9, <3.10"]
enable_resolves = true

[python.resolves]
python-default = "default.lock"

[cli.alias]
day-01 = "src/day/01/find_elf_carrying_most_calories.py -- inputs/day_01.txt"
day-02 = "src/day/02/run_rock_paper_scissors_tournament.py -- inputs/day_02.txt"
# For Day 2 part 2, run:
# ./pants run day-02 --part-two
